name: workflow

on: 
  push: 
    branches: 
      - main
    paths-ignore:
      - 'README.md'
jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: lint code
        run: echo "Linting code..."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: | 
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }} # Use the commit SHA
        run: |  
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  deployment:
    name: Deployment
    needs: integration
    runs-on: self-hosted #means app runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker image from ECR
        env: 
          AWS_ECR_LOGIN_URL: ${{ secrets.AWS_ECR_LOGIN_URL }}
          IMAGE_TAG: ${{ github.sha }} # Use the commit SHA
        run: |
          docker pull $AWS_ECR_LOGIN_URL:$IMAGE_TAG
      - name: Stop and remove existing container
        run: |
          docker stop mltest || true
          docker rm mltest || true

      - name: Run Docker image to server users
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ECR_LOGIN_URL: ${{ secrets.AWS_ECR_LOGIN_URL }}
          IMAGE_TAG: ${{ github.sha }} # Use the commit SHA
        run: |
          docker run -d -p 8080:8080 --ipc="host" --name=mltest -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" -e "AWS_REGION=$AWS_REGION" $AWS_ECR_LOGIN_URL:$IMAGE_TAG
      - name: Clean previous images and containers
        run: |
          docker system prune -f