name: workflow

on: 
  push: 
    branches: 
      - main
    paths:
      - '8-NetworkSecurity/**' # Trigger if anything in this folder changes
      - '!8-NetworkSecurity/README.md' # Ignore README changes
jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: lint code
        run: echo "Linting code..."